### PR TITLE
Fix/550/592/649/658/628/UI improvements

### LINKED ISSUE #550: When changing a member role the admin under changing role? popup the member name is prefix with '$'
Steps:
1.add new members to the team with editor/viewer role
2.goto members list after inviting
3.click on dropdown to change member role
4.change a member role to admin role
5.view changing role popup

Expected:
UI text should not have spelling mistakes
Actual:
$ is prefix with user name
image

### LINKED ISSUE #592: "Activate Workspace" dropdown is not showing available workspace in it.
1. Login to sparrow 
2. Create a new Workspace
3. Go to the active workspace
4. Tap on the Workspace setting.
5. Tap on Delete Workspace
6. Enter the Workspace name and tap on delete workspace
7. Tap on Activate Workspace dropdown

**Expected Outcome**
The remaining workspace should show in the dropdown

**Actual Outcome**
dropdown is not showing anything, so not able to proceed

Attachment
https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/ESOA2yi1LyhDqxaHBU8WrXYBcPN6QgOZz_GMwjZqbIoUeQ?e=kcRkIG

### LINKED ISSUE #628: UI overlapping (search and response)
**Steps to reproduce**
1. Run the one API, so we should get a response.
2. Tap on search.

**Expected Outcome**
Ui should not overlap.

**Actual Outcome**
UI is overlapped.

image

### LINKED ISSUE #649: In active sync, deleted API in code should appear as grey colour in sparrow
### **🐛 Bug Report**

In active sync, deleted API in code should appear as grey colour in sparrow 

**Steps to reproduce:**

- In your code select "active sync" branch then Login to sparrow 
- import the active sync collection and see number of API in user folder 
- Now in code go to user.controler.ts and delete some API and then run the code 
- Now in sparrow check deleted APIs

**Expected Behaviour:** deleted APIs should appear in grey colour 
Screenshot 2024-03-20 at 12 20 05 PM

**Actual Behaviour:** APIs are not appearing in grey colour 
Screenshot 2024-03-20 at 12 19 04 PM

### LINKED ISSUE #658: In "Select Primary Branch "dropdown " None" option should not be present, if it is not working.
1. Tap on collection.
2. Give the local host link.
3. Enable Active Sink
4. paste the path of the repository
5. Tap on the "Select Primary Branch" dropdown.
6. Select "None".

**Expected Result**
None option should not come with a "Tick" option.
If it is there, then the user should be able to proceed with the "None" option.

**Actual Outcome**
None option is present with a "Tick" option.
After selecting "None" option user is not able to proceed.
image

### PR DESCRIPTION
**Pull request by theketan26**
## Description

closes #550 
closes #592 
closes #649 
closes #658 
closes #628 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build

## Have you tested locally?

- [x] 👍 yes
- [ ] 🙅 no, because I am lazy

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md

### CODE REVIEW

File: src/lib/components/collections/collections-list/request/Request.svelte [hunk 1]
```diff
@@ -476,6 +476,9 @@
     font-weight: 400;
     width: calc(100% - 48px);
   }
+  .api-name-deleted {
+    color: #999999;
```
Comment (LordNayan) [inline src/lib/components/collections/collections-list/request/Request.svelte:480]: Can we take this from config

**Review by gc-codes — APPROVED** [review]
