### PR TITLE
Fix: Code Optimization for Bluk Tab Deletion from LHS

### LINKED ISSUE #2837: [code refactor]: Optimize Multiple Tab Deletion in Method
### Description  
Currently, when deleting multiple tabs, the implementation calls the single-tab deletion function in a loop. This is not an efficient approach and can be improved for better performance and maintainability.  

### Current Implementation  
- Each tab is deleted individually in a loop.  
- This results in multiple database queries and unnecessary re-renders, which could be avoided.  

### Suggested Improvements  
- Delete multiple tabs in **one go** instead of iterating through them.  
- Use **RxDB queries** or another batch operation to handle deletion more efficiently.  
- Explore transaction-based deletion or bulk updates to minimize redundant operations.  

### Expected Benefits  
- **Improved performance** by reducing redundant function calls.  
- **Better database efficiency** with fewer queries.  
- **Cleaner and maintainable code** with a structured deletion approach.

### PR DESCRIPTION
**Pull request by anish-techdome**
### Description
This PR optimizes the multiple tab removal logic to improve efficiency and maintainability. The previous implementation was already functional, and this change does not introduce any functional modifications—only a code-level improvement to enhance performance and readability.

### Add Issue Number
Fixes #2837 

### Add Screenshots/GIFs
Deletion and Activating the the last tab from the tab list.
https://github.com/user-attachments/assets/1a2a7bf3-42cc-4f12-8433-f4b4e5005dd1

### Contribution Checklist:
- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **I have linked an issue to the pull request.**
- [x] **I have linked a PR type label to the pull request.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](../../docs/CONTRIBUTING.md).**

### CODE REVIEW

File: apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts [hunk 1]
```diff
@@ -810,14 +810,49 @@ export default class CollectionsViewModel {
...
+  private async removeTabWithChildren(
+    mainEntityId: string,
+    workspaceId: string,
+    entityType: "request" | "collection" | "folder",
+  ): Promise<void> {
+    let childTabs = [];
+
+    // Remove the main tab
+    await this.tabRepository.removeTab(mainEntityId);
+
```
Comment (itsmdasifraza) [inline apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts:839]: get a single tabid by making an query, and push it to tabIdsToDelete, 
we have to delete it in one go only.

**Review by itsmdasifraza — APPROVED** [review]

**Review by Astitva877 — APPROVED** [review]
