### PR TITLE
Fix: Global Search Recent Section Issues & Search Highlighting 

### LINKED ISSUE #2540: Search highlight function is not working in global search.
Expected-

Image

Actual-

Image

### LINKED ISSUE #2557: If user rename anything from LHS panel (collection/folder/All api requests/environment/test flows) then it is not coming in recent section of global search.
1. Open any existing entity mentioned above
2.Rename it from LHS panel
3.Open global search and check the recent section

Expected-
Remaned entity should come in recent section of global search

Actual-
Renamed entity is  coming in recent section

https://techdome-my.sharepoint.com/:v:/g/personal/shreyas_pharande_techdome_net_in/Eb8L_iTdE7FDoPvJ-RSRV30BTUOa_uz9Ji34zcLpITyeEg?e=PSPQoq

### LINKED ISSUE #2835: [bug]: Global Search Recent Section Issue
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Bug Report: Multiple Issues in Recent Section & Environment in Global Search
The following issues have been identified and need to be addressed:  

1. Renamed collection is not appearing in the recent section.  
2. Newly added folder is not appearing in the recent folder section.  
3. Renamed folder is not appearing in the recent section.  
4. The recent request section should sort new/updated requests at the top (newly added request appears in the 3rd place instead).  
5. Newly updated/saved/renamed API is not appearing at the top of the recent REST API section.  
6. In the environment section, the associated team/workspace name is missing.  
7. Recently saved/updated environments are not appearing in the recent list. (If a user updates a global variable, it should also appear in the recent section) (Renamed environments do appear).  
8. Newly updated/saved test flow is not appearing in the recent section.  
9. In the test flow section, the team/workspace name is missing.  

### Expected Result
- Items in the **recent** section should reflect updates immediately.  
- **Sorting** should ensure new/updated items appear at the top.  
- Missing **team/workspace names** should be properly displayed.  

### Actual Result
- Renamed collections, folders, and APIs are **not** appearing in the recent section.  
- Newly added folders are **not** appearing in the recent folder section.  
- The recent request section **does not sort** new/updated requests at the top.  
- Updated/saved environments **do not appear** in the recent list (except renamed ones).  
- Modifying a global variable **does not add it** to the recent section.  
- The **team/workspace name** is missing in both the environment and test flow sections. 

### Steps to reproduce
1. Rename a collection/folder/API and check the recent section.  
2. Add a new folder and verify if it appears in the recent folder section.  
3. Update/save an environment or test flow and check if it appears in the recent list.  
4. Modify a global variable and check the recent section.  
5. Observe the sorting behavior of the recent request section.  

These issues impact the usability of the recent section and environment handling. Fixing them will improve user experience by ensuring updates are properly reflected.  

### Operating System

Windows 11

### PR DESCRIPTION
**Pull request by anish-techdome**
### Description
This PR resolves multiple bugs related to the display and sorting of recently updated entities across various sections. It also introduces **search result highlighting** for better visibility.  

### Recent Section Fixes  
- Renamed collections and folders now appear in the **Recent** section.  
- Newly added folders now appear in the **Recent Folder** section.  
- Recently updated/saved/renamed APIs now correctly move to the **top** of the **Recent API** section.  
- Recent requests are now properly **sorted**, ensuring the latest ones appear at the top.  

### Environment Fixes  
- The **associated team/workspace name** now displays correctly in the environment section.  
- Recently saved/updated environments (including global variable updates) now appear in the **Recent Environment** list.  

### Test Flow Fixes  
- Newly updated/saved test flows now appear in the **Recent** section.  
- team/workspace name now appears in the **Test Flow** section.  

### Search Bar Focus
- Enable the search bar focus state

### Search Text Highlighting
- **Implemented search result highlighting** to improve visibility and user experience.  

### Add Issue Number
- Fixes #2540 
- Fixes #2557 
- Fixes #2835 

### Add Screenshots/GIFs
Recent Section Fixes:
image

Screenshot for text highlighting
image

### Contribution Checklist:
- [ ] **The pull request only addresses one issue or adds one feature.**
- [x] **I have linked an issue to the pull request.**
- [x] **I have linked a PR type label to the pull request.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](../../docs/CONTRIBUTING.md).**

### CODE REVIEW

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

File: .gitignore [hunk 1]
```diff
@@ -44,4 +44,7 @@ dist-ssr
 vite.config.ts.timestamp*
 
 #pnpm lock
-pnpm-lock.yaml
\ No newline at end of file
+pnpm-lock.yaml
+
+
+.eslintignore
```
Comment (Astitva877) [inline .gitignore:50]: why we have pushed this in .gitignore?

**Comment by pratikshinde590** [comment]
Please attach the issue link

File: .gitignore (hunk 1 above)
Comment (anish-techdome) [reply .gitignore]: @Astitva877  Fixed ✅

File: packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte [hunk 2]
```diff
@@ -172,17 +172,17 @@
     {
       key: "collections",
       condition: filteredCollection && filteredCollection[0],
-      items: filteredCollection ? [filteredCollection[0]] : [],
+      items: filteredCollection ? filteredCollection.slice(0, 3) : [],
```
Comment (Astitva877) [inline packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte:175]: We don't need to show three items in the default state. Was there a specific reason for setting it to three?

File: packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte [hunk 3]
```diff
@@ -172,17 +172,17 @@
...
     },
     {
       key: "environments",
       condition: filteredEnvironments && filteredEnvironments[0],
-      items: filteredEnvironments ? [filteredEnvironments[0]] : [],
+      items: filteredEnvironments ? filteredEnvironments.slice(0, 3) : [],
```
Comment (Astitva877) [inline packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte:180]: same as above.

File: packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte [hunk 4]
```diff
@@ -172,17 +172,17 @@
...
     },
     {
       key: "folders",
       condition: filteredFolder && filteredFolder[0],
-      items: filteredFolder ? [filteredFolder[0]] : [],
+      items: filteredFolder ? filteredFolder.slice(0, 3) : [],
```
Comment (Astitva877) [inline packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte:185]: same

File: packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte (hunk 2 above)
Comment (anish-techdome) [reply packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte:175]: @Astitva877  Yes, It was mentioned inside ticket, that In all the sections, the 3 recent options should come. Can you check it once and confirm.

Comment (itsmdasifraza) [reply packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte:175]: 3 should only be shown when search box is empty

**Review by itsmdasifraza — CHANGES_REQUESTED** [review]

File: packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte (hunk 2 above)
Comment (anish-techdome) [reply packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte:175]: @itsmdasifraza  @Astitva877 
I had a discussion with Shreyas, he asked to keep the same old one functionality only, no three recent sections need to show. Let me know your thoughts.

**Comment by pratikshinde590** [comment]
Please attach the issue link

File: packages/@sparrow-common/src/features/global-search/components/RecentItems/sub-components/ItemBar.svelte [hunk 5]
```diff
@@ -1,11 +1,15 @@
...
   export let icon = FolderIcon;
-  export let iconProps = { color: "var(--text-ds-neutral-200)" , width: "16px" , height: "16px" };
+  export let iconProps = {
+    color: "var(--text-ds-neutral-200)",
+    width: "16px",
+    height: "16px",
+  };
   export let data = {};
-
+  console.log("data :>> ", data);
```
Comment (Astitva877) [inline packages/@sparrow-common/src/features/global-search/components/RecentItems/sub-components/ItemBar.svelte:12]: remove console.

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

**Comment by pratikshinde590** [comment]
Please attach the issue link

File: apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts [hunk 6]
```diff
@@ -2202,6 +2203,7 @@ export default class CollectionsViewModel {
           );
         if (res) {
           res.name = newFolderName;
+          res.updatedAt = new Date().toString();
```
Comment (Astitva877) [inline apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts:2206]: shouldn't we use here 
toISOString() in place of toString()?

Comment (anish-techdome) [reply apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts]: @Astitva877 Fixed ✅

**Review by Astitva877 — APPROVED** [review]
